name: Bump Version

on:
  pull_request:
    types: [closed]

jobs:
  bump-version:
    runs-on: macos-latest
    if: ${{ github.event.pull_request.merged && github.head_ref == 'code-complete-develop' }}

    steps:
      - uses: actions/checkout@v2
        with:
          ref: develop
      
      - name: Import GPG key
        id: import_gpg
        uses: scorebet/ghaction-import-gpg@v3
        with:
          gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.GPG_PASSPHRASE }}
      
      - name: setup git identity
        id: git-identity
        run: |
          user_name='scorebet-bot'
          user_email='scorebet-bot@thescore.com'
          
          git config --global user.name $user_name
          git config --global user.email $user_email
          git config --global commit.gpgsign true
      
          echo "::set-output name=user_name::$user_name"
          echo "::set-output name=user_email::$user_email"

      - name: Get marketing version
        id: marketing-version
        run: |
          marketing_version=$(/usr/libexec/PlistBuddy -c "Print :CFBundleShortVersionString" "Sources/theScore Bet/Supporting Files/Info.plist")

          new_marketing_version=$(echo $marketing_version | awk 'BEGIN { FS="." } { print $1 "." $2+1 ".0" }')

          echo "Saving new marketing version $new_marketing_version"
          echo "::set-output name=new_marketing_version::$new_marketing_version"
      
      - name: Update marketing version
        working-directory: Sources
        run: agvtool new-marketing-version "${{ steps.marketing-version.outputs.new_marketing_version }}"

      - name: Create PR
        uses: scorebet/create-pull-request@v3
        with:
          labels: Bump version
          branch: bump-version-develop
          base: develop 
          title: "Bump version v${{ steps.marketing-version.outputs.new_marketing_version }}"
          body: |
            :crown: *An automated PR*

            To Do
            ----
            - [ ] Create new repo milestone
