name: Code Complete

on:
  workflow_dispatch:

jobs:
  code-complete:
    runs-on: macos-latest

    steps:
      - run: |
          brew install xmlstarlet
      
      - run: |
          xml -version
          
      - uses: actions/checkout@v2
        with:
          ref: release-candidate

      - name: Reset to develop branch
        run: |
          git fetch origin develop:develop
          git reset --hard develop

      - name: Get marketing version
        id: marketing-version
        run: |
          marketing_version=$(/usr/libexec/PlistBuddy -c "Print :CFBundleShortVersionString" "Sources/Dummy/Info.plist")

          echo "Saving marketing version $marketing_version"
          echo "::set-output name=marketing_version::$marketing_version"

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          labels: Code complete
          branch: code-complete-develop
          title: "v${{ steps.marketing-version.outputs.marketing_version }} code complete"
          body: |
            :snowflake: Merge `develop` into `release-candidate`

            :warning: Do NOT squash merge
